name: Go Build for Linux

on:
  push:
    branches:
      - main

permissions:
  contents: write


jobs: 
  build: 
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Get latest commit message
        id: get_commit_message
        run: |
          echo "commit_message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
      
        



      - name: Build files
        if: ${{ contains(env.commit_message, '--build') }}
        uses: ./.github/actions/custom-build
        with:
          workdir: ${{github.workspace}}

      - name: Commit changes
        if: ${{ contains(env.commit_message, '--build') }}
        run: |
          git config --global user.name "${{ env.author }}"
          git config --global user.email "qq623589@gmail.com"
          
          git add proxies
      
          git commit -a -m "Built go files for commit: $commit_hash"
      
          git push --force 